#!/bin/bash

g=$(tput setaf 2)
b=$(tput setaf 4)
rs=$(tput sgr0)

idea_sh='/var/lib/idea-IC-145.258.11/bin/idea.sh'

file="$1"


if [[ -z "$file" ]]; then
  $idea_sh
else
  file_abs=$(realpath "$file")
  dir=$(dirname "$file_abs")
  project="$dir"

  # Find outermost project dir
  while [[ "$dir" != "/" ]]; do
    if [[ -d "$dir/.idea" ]]; then
      project="$dir"
    fi
    dir=$(realpath "$dir/..")
  done
  file_rel=${file_abs#$project}
  echo "Opening ${g}${project}${b}${file_rel}${rs}"
  exec $idea_sh "$project" --line 1 "$file"  > /dev/null 2>&1 &
fi
