#!/bin/bash

r=$(tput setaf 1)
g=$(tput setaf 2)
b=$(tput setaf 4)
rs=$(tput sgr0)

idea_sh='/var/lib/idea-IC-162.2032.8/bin/idea.sh'

file="$1"


if [[ -z "$file" ]]; then
  $idea_sh
else
  file_abs=$(realpath "$file")

  # Arg is dir or file
  if [[ -d "$file_abs" ]]; then
    dir="$file_abs"
  elif [[ -f "$file_abs" ]]; then
    dir=$(dirname "$file_abs")
  else
    echo "${r}Not found: ${file_abs}${rs}" >&2
    exit 1
  fi

  dir_given="$dir"

  # Find outermost project dir
  while [[ "$dir" != "/" && -z "$project" ]]; do
    if [[ -d "$dir/.idea" ]]; then
      project="$dir"
    fi
    dir=$(realpath "$dir/..")
  done

  # None found, use given dir
  if [[ -z "$project" ]]; then
    project="$dir_given"
  fi


  # Show info
  file_rel=${file_abs#$project}
  echo "Opening ${g}${project}${b}${file_rel}${rs}"

  # Launch
  if [[ -d "$file_abs" ]]; then
    exec $idea_sh "$project" > /dev/null 2>&1 &
  else
    exec $idea_sh "$project" --line 1 "$file"  > /dev/null 2>&1 &
  fi

fi
